- app/src/main/java/com/example/boeing301house/Circle.java
- app/src/main/java/com/example/boeing301house/Oval.java
- app/src/main/java/com/example/boeing301house/Rectangle.java
- app/src/main/java/com/example/boeing301house/Shape.java
Got rid of shape abstract superclass and subclasses
> Removed irrelevant classes (from lab)

- app/src/main/res/layout/item_list_activity.xml
> created list_activity xml

- app/src/main/java/com/example/boeing301house/Item.java
- app/src/main/java/com/example/boeing301house/ItemAdapter.java
- app/src/main/res/layout/item_cell.xml
added 2 classes and 1 xml, so that I can start development of list_activity.java soon
> Added item.java, and item_cel.xml, and the item adapter

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/boeing301house/AddEditItemFragment.java
- app/src/main/java/com/example/boeing301house/Item.java
- app/src/main/java/com/example/boeing301house/ItemListActivity.java
- app/src/main/res/layout/add_edit_item_fragment.xml
- app/src/main/res/layout/item_list_activity.xml
fixed problems from Danny branch
> done 01.01.01

- app/src/main/java/com/example/boeing301house/ItemAdapter.java
- app/src/main/java/com/example/boeing301house/ItemListActivity.java
> Fixed selection bug (hopefully)

- app/build.gradle.kts
- app/src/main/java/com/example/boeing301house/AddEditItemFragment.java
- app/src/main/java/com/example/boeing301house/ItemListActivity.java
- app/src/main/res/layout/activity_item_list.xml
- app/src/main/res/layout/fragment_add_edit_item.xml
> fixed item bug

- app/src/main/java/com/example/boeing301house/AddEditItemFragment.java
- app/src/main/java/com/example/boeing301house/ItemListActivity.java
> item detail bug fixed

- app/src/main/res/drawable/ic_close_button_48dp.xml
- app/src/main/res/drawable/ic_profile_button_96dp.xml
- app/src/main/res/drawable/roundedbutton.xml
- app/src/main/res/layout/user_login.xml
- app/src/main/res/layout/user_profile.xml
- app/src/main/res/menu/ab_user_profile_bar.xml
> User Profile and Login xml

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/boeing301house/UserProfileActivity.java
- app/src/main/res/layout/user_profile.xml
> Implemented partial user profile functionality

- app/src/main/java/com/example/boeing301house/ItemListActivity.java
- app/src/main/res/layout/activity_item_list.xml
Just added commented out listeners for launching the button's respective fragments, which each have not been implemented yet
> Added the framework code for filter/sort buttons

- app/src/main/java/com/example/boeing301house/ItemListActivity.java
- app/src/main/res/layout/activity_item_list.xml
- app/src/main/res/menu/ab_item_list_appbar.xml
> fixed description/make search

- app/src/main/java/com/example/boeing301house/ItemListActivity.java
Added intent when clicking on profile Icon
> Added opening of Profile Activity

- app/src/main/java/com/example/boeing301house/UserProfileActivity.java
- app/src/main/res/layout/edit_username_dialog.xml
- app/src/main/res/layout/user_profile.xml
- app/src/main/res/values/strings.xml
Created button and dialog for username editing, dialog appear on button click
> Button and Dialog creationg for username editing

- app/src/main/java/com/example/boeing301house/AddEditItemFragment.java
- app/src/main/java/com/example/boeing301house/ItemListActivity.java
- app/src/main/java/com/example/boeing301house/ItemViewActivity.java
- app/src/main/res/layout/activity_item_view.xml
EDIT DONE need to do firestore, then 1000000% complete
> edit feature done except need to implement firestore for it

- app/src/main/java/com/example/boeing301house/MainActivity.java
- app/src/main/java/com/example/boeing301house/UserProfileActivity.java
implemented local storage for username and userid
> Cache username and userid

- app/src/main/java/com/example/boeing301house/AddEditItemFragment.java
> Added toast for upcoming features

- app/src/androidTest/java/com/example/boeing301house/andresTestFile.java
> Created tests for Delete, Edit and Confirm, Edit and Discard, and Total

- app/src/main/java/com/example/boeing301house/ItemListActivity.java
- app/src/main/java/com/example/boeing301house/MainActivity.java
Now storing data both on cache and firebase
> Implemented user data storage in Firebase

- app/src/main/res/layout/fragment_tags.xml
Comment describes that tags are still in implementation
> Added comment in tags fragment

- app/src/main/java/com/example/boeing301house/DBConnection.java
- app/src/main/java/com/example/boeing301house/Itemlist/ItemListActivity.java
- app/src/main/java/com/example/boeing301house/MainActivity.java
Moving UUID information and storing into DBConnection
> DBConnection Update

- app/src/main/java/com/example/boeing301house/Itemlist/ItemListActivity.java
> Deleted Duplicate Functionality

- app/src/main/java/com/example/boeing301house/TagsFragment.java
Fixed back functionality, also added onClickListener to Confirm button
> Fixed back button on Tags

- app/build.gradle.kts
- app/src/main/java/com/example/boeing301house/Itemlist/ItemList.java
- app/src/main/java/com/example/boeing301house/TagsFragment.java
- app/src/main/res/layout/fragment_tags.xml
User can now add their own tags and the tags are added to the item on confirm.
> Added Tag Functionality

- app/src/main/java/com/example/boeing301house/Itemlist/ItemList.java
> ItemList update builder

- app/src/main/java/com/example/boeing301house/Item.java
- app/src/main/java/com/example/boeing301house/ItemBuilder.java
- app/src/main/java/com/example/boeing301house/addedit/AddEdit.java
- app/src/main/java/com/example/boeing301house/addedit/AddEditImageAdapter.java
- app/src/main/java/com/example/boeing301house/addedit/AddEditItemFragment.java
- app/src/main/java/com/example/boeing301house/itemlist/ItemList.java
- app/src/main/java/com/example/boeing301house/itemview/CarouselAdapter.java
- app/src/main/java/com/example/boeing301house/itemview/ItemViewActivity.java
NEED TO FIX DELETE FUNCTIONALITY FOR IMAGES
- delete stored images attached to items whe item deleted
- delete 'new' stored images if editing + cancelled
- delete no longer used images if editing + confirm
- deleting an image when its from gallery (wont have unique id in firebase)
> image storing in item + comments, cleanup. 

- app/src/main/java/com/example/boeing301house/addedit/AddEditItemFragment.java
- app/src/main/java/com/example/boeing301house/itemview/ItemViewActivity.java
gallery photos weren't distinguishable, now they are so it doesn't delete the same photo in another item
> adding from gallery fix -> photos now distinguishable

- app/src/main/java/com/example/boeing301house/DBConnection.java
- app/src/main/java/com/example/boeing301house/Tags.java
- app/src/main/java/com/example/boeing301house/TagsFragment.java
- app/src/main/java/com/example/boeing301house/itemlist/FilterFragment.java
- app/src/main/java/com/example/boeing301house/itemlist/ItemList.java
- app/src/main/java/com/example/boeing301house/itemlist/ItemListActivity.java
- app/src/main/java/com/example/boeing301house/itemlist/ItemListController.java
- app/src/main/res/layout/fragment_filter.xml
still need to make storage user centric
> user centric list

- app/src/androidTest/java/com/example/boeing301house/ListTestUITest.java
I still want to add the filter and sort tests for tags tommorow, but I'll likely get this merged to avoid future conflicts
> Created a main ListTestUI file for tests, and finished add/delete tags test

- app/src/androidTest/java/com/example/boeing301house/MainActivityTest.java
- app/src/androidTest/java/com/example/boeing301house/ProfileTests.java
Profile test and MainActivity Test update
> Profile test and MainActivity Test update
